sudo: required

language: generic

services: 
  - docker



deploy:
  provider: elasticbeanstalk
  region : "ap-northeast-2"
  app: "react-app"
  env: "React-app-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-274062116193"
  bucket_path: "react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY